### ISSUE TITLE
`rebootmgr.service` runs into D-Bus error spawning a high amount of processes

### ISSUE THREAD

**Issue by Martchus** [SUSE/rebootmgr#15]
### Observation
On a VM running on Leap 15.4 I've just observed very weird behavior. The systemd service failed but there were still tons of processes associated to it:

```
martchus@backup-vm:~> sudo systemctl status rebootmgr.service
× rebootmgr.service - Reboot Manager
     Loaded: loaded (/usr/lib/systemd/system/rebootmgr.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2023-03-02 15:38:30 CET; 1min 55s ago
       Docs: man:rebootmgrd(8)
             man:rebootmgrctl(1)
    Process: 17861 ExecStart=/usr/sbin/rebootmgrd (code=exited, status=1/FAILURE)
   Main PID: 17861 (code=exited, status=1/FAILURE)
      Tasks: 246 (limit: 4915)
     CGroup: /system.slice/rebootmgr.service
             ├─   392 /usr/sbin/rebootmgrd
… skipped ~ 200 lines
             ├─ 24825 /usr/sbin/rebootmgrd
```

Unfortunately I'm not sure how to reproduce the issue again. It happened one time and after cleaning up the mess of processes (as described below) everything worked fine again.

The service was restarting several times. This always looks like this:
```
Feb 26 03:35:18 backup-vm systemd[1]: Starting Reboot Manager...
Feb 26 03:35:38 backup-vm systemd[1]: Started Reboot Manager.
Mar 02 03:02:34 backup-vm systemd[1]: rebootmgr.service: Unexpected error response from GetNameOwner(): Connection terminated
Mar 02 03:02:34 backup-vm systemd[1]: rebootmgr.service: Deactivated successfully.
Mar 02 03:02:34 backup-vm systemd[1]: rebootmgr.service: Unit process 1258 (rebootmgrd) remains running after unit stopped.
Mar 02 03:38:45 backup-vm systemd[1]: Starting Reboot Manager...
Mar 02 03:38:45 backup-vm rebootmgrd[27964]: org.opensuse.RebootMgr is already reserved
Mar 02 03:40:15 backup-vm systemd[1]: rebootmgr.service: start operation timed out. Terminating.
Mar 02 03:40:15 backup-vm systemd[1]: rebootmgr.service: Failed with result 'timeout'.
Mar 02 03:40:15 backup-vm systemd[1]: rebootmgr.service: Unit process 1258 (rebootmgrd) remains running after unit stopped.
Mar 02 03:40:15 backup-vm systemd[1]: rebootmgr.service: Unit process 27964 (rebootmgrd) remains running after unit stopped.
Mar 02 03:40:15 backup-vm systemd[1]: Failed to start Reboot Manager.
Mar 02 03:40:15 backup-vm systemd[1]: rebootmgr.service: Scheduled restart job, restart counter is at 1.
Mar 02 03:40:15 backup-vm systemd[1]: Stopped Reboot Manager.
Mar 02 03:40:15 backup-vm systemd[1]: Starting Reboot Manager...
…
Mar 02 08:08:42 backup-vm systemd[1]: Starting Reboot Manager...
Mar 02 08:08:42 backup-vm rebootmgrd[15675]: org.opensuse.RebootMgr is already reserved
Mar 02 08:10:12 backup-vm systemd[1]: rebootmgr.service: start operation timed out. Terminating.
Mar 02 08:10:12 backup-vm systemd[1]: rebootmgr.service: Failed with result 'timeout'.
Mar 02 08:10:12 backup-vm systemd[1]: rebootmgr.service: Unit process 1258 (rebootmgrd) remains running after unit stopped.
… skipped the remaining processes here; systemd basically lists all remaining processes accumulated so far and the list grows longer with every restart
```

So the first error is different and likely the culprit. However, the subsequent error handling is also far from ideal. Especially since at some point the error is turning into the following:
```
Mar 02 14:38:38 backup-vm systemd[1]: Starting Reboot Manager...
Mar 02 14:38:38 backup-vm rebootmgrd[2911]: Connection to D-BUS system message bus failed: The maximum number of active connections for UID 0 has been reached.
Mar 02 14:38:38 backup-vm systemd[1]: rebootmgr.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 14:38:38 backup-vm systemd[1]: rebootmgr.service: Failed with result 'exit-code'.
Mar 02 14:38:38 backup-vm systemd[1]: rebootmgr.service: Unit process 1258 (rebootmgrd) remains running after unit stopped.
```

Invoking `sudo systemctl kill rebootmgr.service` to get rid of all these processes (and freeing the D-Bus connections) helped. Then I could start the service again normally via `sudo systemctl start rebootmgr.service` and only one process was spawned.

### Expected behavior
1. If there's an error, the service fails cleanly. If it is worth retrying then this should of course be done but not leaving lingering processes around.
2. The first error should likely not have had occurred in the first place.

**Comment by thkukuk** [comment]
Your main problem was, that your dbus broker did not work as expected. This looks very much like somebody restarted the dbus daemon...

That systemd restarts rebootmgrd in case of a failure is correct and required behavior: you don't want that an user stops rebootmgrd with an DoS attack and thus prevents the machine from applying security updates.
Cleaning up failed services is the job of systemd.
But: from your output it looks like rebootmgrd was still running and working, systemd just had a communication problem with dbus daemon and for this reason did restart rebootmgrd again and again in the wrong assumption, that rebootmgrd had the problem.
There is nothing rebootmgrd can do if systemd starts that again and again.
rebootmgrd quits itself immediately after the error messages in your output. If this a "exit(1)" function call does not quit the application on your system, there was much more damaged. Also nothing we can fix.
But a running, non-functional dbus daemon can today a lot of harm, but this is nothing rebootmgr can fix or workaround.
I don't know what was the culprit of your problems, but rebootmgrd itself did behave correct and as expected. If the environment is broken, it cannot do more than quit itself. Why neither the kernel nor systemd removed a dead process, I don't know.

**Comment by Martchus** [comment]
Thanks for the response. I'll try to check other logs to find out what the problem with the D-Bus daemon was. Since nothing else failed (and you state yourself "But a running, non-functional dbus daemon can today a lot of harm") I didn't suspect that the D-Bus daemon had an issue.

> If this a "exit(1)" function call does not quit the application on your system, there was much more damaged.

Yes, I also find this quite strange. I first invoked `kill` manually on some of the PIDs and it worked, then `systemd kill` and all were gone. Why the processes were still lingering after the `exit(1)` call is very mysterious.
