### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by tacerus** [SUSE/rebootmgr#16]
Hi,

apologies, this is not an issue, but I didn't find a better place to ask.

I understand we officially only ship this tool in the Transactional Server Module for SLE. However are there any objections to using it on regular SLES (15.4, possibly older)? Are there any specific dbus requirements?

Cheers,
Georg

**Comment by thkukuk** [comment]
rebootmgr woks on regular SLES, too, but it's of course not supported and you should make sure you have at least version 1.3.

**Comment by tacerus** [comment]
Got it, thank you very much!
