### ISSUE TITLE
If `etcd-lock` strategy is used in a build where it was removed, it is silently ignored.

### ISSUE THREAD

**Issue by Laikulo** [SUSE/rebootmgr#19]
If rebootmgr was compiled w/o etcd support (as is currently in Leap), and the user specifies etcd-lock as a strategy, the daemon starts w/o error or warning, and the normal best-effort logic takes precedence.

This can lead to unexpected concurrent reboots, and unhappy corosync clusters.

It would be preferable to bail if etcd-lock is specified when not allowed.

**Comment by thkukuk** [comment]
This is impossible, as etcd support got completely removed some years ago.
If  Leap is using an old version, somebody should update that, I have nothing to do with that.
