### ISSUE TITLE
 rebootmgrctl reboot fast not ignoring maintenance window

### ISSUE THREAD

**Issue by brycemcl** [SUSE/rebootmgr#4]
"rebootmgrctl reboot fast" doesn't perform as expected when outside of the maintenance window. I have etcd-lock setup and when outside of the maint-window rebootmgr gets a lock then doesn't reboot when the "rebootmgrctl reboot fast" command is run.

When I start the /opensuse.org/rebootmgr/locks/default/data key is set to

 
{
  "max":1,
  "holders":[
  ]
}

Then I run the following commands

i52:~ # rebootmgrctl status
Status: Reboot not requested
Etcd locks:
        Reboot group: default
        Available: 1
        Max: 1
i52:~ # rebootmgrctl get-window
Maintenance window is set to *-*-* 00:00:00, lasting 03h00m.
i52:~ # rebootmgrctl reboot fast
i52:~ # rebootmgrctl status
Status: Reboot not requested
Etcd locks:
        Reboot group: default
        Available: 0
        Max: 1

        Machine ID:
        f0c7124b043c4935a1b6918d79a0f8d5
i52:~ # rebootmgrctl --version
rebootmgrctl (rebootmgr) 0.16

At this point, the /opensuse.org/rebootmgr/locks/default/data key is set to

{
  "max":1,
  "holders":[
    "f0c7124b043c4935a1b6918d79a0f8d5"
  ]
}

Then I run
i52:~ # rebootmgrctl unlock f0c7124b043c4935a1b6918d79a0f8d5
Released lock from etcd for machine with ID f0c7124b043c4935a1b6918d79a0f8d5
i52:~ # rebootmgrctl set-window 00:00:00 23h59m
i52:~ # rebootmgrctl reboot fast

At this point the machine reboots

**Comment by thkukuk** [comment]
This are even two bugs: that the maintenance window will not be ignored in fast reboot mode, and that the lock will not be freed if we cancel reboot.
Both should be fixed now.
