### ISSUE TITLE
Make `etcd` optional to compile.

### ISSUE THREAD

**Issue by ahkok** [SUSE/rebootmgr#6]
It's currently not possible to compile this project without etcd. It appears that even without etcd support this project may be useful to people, given the readme text. I'm looking into adding rebootmgr to clearlinux, but I'd like to add it without having to add etcd.

**Comment by thkukuk** [comment]
Version 0.18 will not compile in etcd support if it does not find libcetcd.

**Comment by ahkok** [comment]
wow, thanks a ton, as well for making a nice `dist` release and uploading the tarball! You've made my day!
