### ISSUE TITLE
Conflict with gettid with latest Glibc 2.30.

### ISSUE THREAD

**Issue by santoshkumarlaxminarayanrai** [SUSE/rebootmgr#7]
log_msg.c:30:1: error: static declaration of 'gettid' follows non-static declaration
   30 | gettid (void)
      | ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from log_msg.c:24:
/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
make[2]: *** [Makefile:428: log_msg.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/util.Tpo .deps/util.Po
mv -f .deps/config_file.Tpo .deps/config_file.Po
mv -f .deps/rebootmgrctl.Tpo .deps/rebootmgrctl.Po
mv -f .deps/rebootmgrd.Tpo .deps/rebootmgrd.Po
make[2]: Leaving directory '/builddir/build/BUILD/rebootmgr-0.18/src'
make[1]: *** [Makefile:411: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/rebootmgr-0.18'
make: *** [Makefile:352: all] Error 2

**Comment by thkukuk** [comment]
Got already fixed a month ago.

**Comment by santoshkumarlaxminarayanrai** [comment]
Thanks for the update for that change I couldn't find the commit. The change is related to libeconf compilation flag checking. 

Note: In release tags I can find 0.20 is latest released tar, but 0.18 is still tagged as latest release.
I am trying to compile v0.20 with libeconf support and getting below error :

Making all in man
make[2]: Entering directory '/builddir/build/BUILD/rebootmgr-0.20/man'
make[2]: Leaving directory '/builddir/build/BUILD/rebootmgr-0.20/man'
make[2]: *** No rule to make target 'rebootmgrd.8', needed by 'all-am'.  Stop.
make[1]: *** [Makefile:416: all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/rebootmgr-0.20'
make: *** [Makefile:357: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.7KjxDy (%build)
